package com.webdemo.controller;

import java.util.Date;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import com.webdemo.accessingdatamysql.CarQuote;
import com.webdemo.accessingdatamysql.CarQuoteRepository;
import com.webdemo.accessingdatamysql.Details;
import com.webdemo.accessingdatamysql.DetailsRepository;
import com.webdemo.accessingdatamysql.MarksRepository;
import com.webdemo.accessingdatamysql.User;
import com.webdemo.accessingdatamysql.UserRepository;

@Controller
public class GreetingController {
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	@Autowired
	private DetailsRepository detailsRepository;
	@Autowired
	private MarksRepository marksRepository;
	@Autowired
	private CarQuoteRepository carQRepository;
	
	@PostMapping("/login")
	public String greeting(@RequestParam(name = "name", required = false, defaultValue = "World") String name,
			@RequestParam(name = "email", required = false, defaultValue = "s@gmail.com") String email, Model model, HttpSession session) {

		session.setAttribute("userName", name);
		session.setAttribute("userEmail", email);

		// putting the name and email in the database spring_db
		User userDetails = new User();
		userDetails.setName(name);
		userDetails.setEmail(email);
		userRepository.save(userDetails);
		
		// setting the name and email to the Model greeting.html
		model.addAttribute("name", name);
		model.addAttribute("email", email);
		System.out.println("Calling the /greeting get method.");
		// add name and email to database spring_db
		return "userdetails";
	}
	@PostMapping("/details")
	public String details(@RequestParam(name = "name", required = true) String name,
			@RequestParam(name = "email", required = true) String email, 
			@RequestParam(name = "firstName", required = true) String firstName,
			@RequestParam(name = "suranme", required = true) String surname,
			@RequestParam(name = "age", required = true) int age,
			@RequestParam(name = "year", required = true) int year,			
			Model model, HttpSession session) {

		
		String userName = (String)session.getAttribute("userName");
		String userEmail = (String) session.getAttribute("userEmail");
		
		
		if(userName == null) {
			// you are not authorised to view this page
		}
		
		// putting the name and email in the database spring_db
		Details details = new Details();
		details.setName(name);
		details.setEmail(email);
		details.setFirstName(firstName);
		details.setSurname(surname);
		details.setAge(age);
		details.setYear(year);
		
		detailsRepository.save(details);
		
		System.out.println("Calling the /greeting get method.");
		// add name and email to database spring_db
		model.addAttribute("userDetails", detailsRepository.findAll());
		
		// return all the name and email values from spring_db
		return "viewall";
	}
	
	@PostMapping("/carquote")
	public String getCarquote(@RequestParam(name = "carName", required = true) String carName,
			@RequestParam(name = "carYear", required = true) String carYear, 
			@RequestParam(name = "firstName", required = true) String firstName,
			@RequestParam(name = "suranme", required = true) String surname,
			@RequestParam(name = "age", required = true) int age,
			@RequestParam(name = "year", required = true) int year,			
			Model model, HttpSession session) {

		
		String userName = (String)session.getAttribute("userName");
		String userEmail = (String) session.getAttribute("userEmail");
		
		
		if(userName == null) {
			// you are not authorised to view this page
		}
		
		// putting the name and email in the database spring_db
		CarQuote carQuote = new CarQuote();
		carQuote.setCarName(carName);
		carQuote.setCarYear(carYear);
		carQuote.setFirstName(firstName);
		carQuote.setSurname(surname);
		carQuote.setAge(age);
		carQuote.setYear(year);
		
		carQRepository.save(carQuote);
		
		System.out.println("Calling the /greeting get method.");
		model.addAttribute("name", session.getAttribute("userName"));
		model.addAttribute("email", session.getAttribute("userEmail"));
		
		// return all the name and email values from spring_db
		return "userdetails";
	}

	@GetMapping("/viewall")
	public String viewall(Model model) {

		model.addAttribute("userDetails", userRepository.findAll());
	
		// return all the name and email values from spring_db
		return "viewall";
	}
	
	@GetMapping("/insurancequote")
	public String getInsuranceQuote(Model model, HttpSession session) {

		model.addAttribute("name", session.getAttribute("userName"));
		model.addAttribute("email", session.getAttribute("userEmail"));
	
		// return all the name and email values from spring_db
		return "insurancequote";
	}
	
	@GetMapping("/marklist")
	public String markList(@RequestParam(name = "email", required = true) String email, Model model) {

//		// randomly insert marks for this id. this is just a simulation
//		Marks mark = new Marks();
//		mark.setId(id);
//		mark.setMaths((int) (Math.random() * 100));
//		mark.setEnglish((int) (Math.random() * 100));
//		mark.setDsp((int) (Math.random() * 100));
//		mark.setMpmc((int) (Math.random() * 100));
//
//		marksRepository.save(mark);

		model.addAttribute("markDetails", marksRepository.findByEmail(email));

		// return all the name and email values from spring_db
		return "marklist";
	}
}